language: erlang
script: "make ci"
services:
  - mongodb
  - rabbitmq
otp_release:
  - R15B01
# whitelist
branches:
  only:
    - master
    - develop
    - travis
notifications:
  email:
    - a.sizov@dev1team.net
