language: erlang
script: "make all"
otp_release:
  - R15B01
# whitelist
branches:
  only:
    - master
    - develop
notifications:
  email:
    - a.sizov@dev1team.net
    - d.klionsky@dev.powermemobile.com